# Generated by Django 5.0.7 on 2024-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Student', 'Student')], default='Student', max_length=100),
        ),
    ]
