# Generated by Django 5.0.7 on 2024-08-07 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateTimeField()),
                ('submission_date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('document', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dasturlashga ilk qadam', 'Dasturlashga ilk qadam'), ('Dasturlashni o"rganishdagi xatolar', 'Dasturlashni o"rganishdagi xatolar')], max_length=150)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Unapproved', 'Unapproved')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(max_length=150)),
                ('notification', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('MEN', 'MEN'), ('FEMALE', 'FEMALE')], max_length=10, null=True)),
                ('date_of_bith', models.DateTimeField()),
                ('joining_date', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=11)),
                ('adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('academics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school_management.academics')),
                ('send_student', models.BooleanField(default=True)),
                ('send_parent', models.BooleanField(default=False)),
            ],
            bases=('school_management.academics',),
        ),
        migrations.AddField(
            model_name='academics',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.school'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Unapproved', 'Unapproved')], max_length=150)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.school')),
                ('select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.section')),
            ],
        ),
        migrations.AddField(
            model_name='academics',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.section'),
        ),
    ]
